image: mirzadipradhana/node:14.16.0-alpine

.cache: &global_cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .npm/

before_script:
  - which yarn
  - echo @warungpintar:registry=https://gitlab.warungpintar.co/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ >> ~/.npmrc
  - echo //gitlab.warungpintar.co/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN} >> ~/.npmrc

stages:
  - release

release:
  stage: release
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn release
  only:
    - master
  tags:
    - gke-node
